var mongoose = require('mongoose');
var Schema = mongoose.Schema;

userSchema = new Schema( {
	username: String,
	c1_sub1:Number,
	c2_sub1:Number,
    c3_sub1:Number,
    c1_sub2:Number,
    c2_sub2:Number,
    c3_sub2:Number,
    c1_sub3:Number,
    c2_sub3:Number,
    c3_sub3:Number,
    c1_sub4:Number,
    c2_sub4:Number,
    c3_sub4:Number,
    c1_sub5:Number,
    c2_sub5:Number,
    c3_sub5:Number,
    c1_ele1:Number,
	c2_ele1:Number,
    c3_ele1:Number,
    c1_ele2:Number,
    c2_ele2:Number,
    c3_ele2:Number,
    c1_ele3:Number,
    c2_ele3:Number,
    c3_ele3:Number,
    c1_mp1:Number,
	c2_mp1:Number,
    c3_mp1:Number,
    c1_mp2:Number,
    c2_mp2:Number,
    c3_mp2:Number,
    sub1:String,
    sub2:String,
    sub3:String,
    sub4:String,
    sub5:String,
    ele1:String,
	ele2:String,
	ele3:String,
	mp1:String,
	mp2:String
}),
Marks = mongoose.model('Marks', userSchema);

module.exports = Marks;